### ISSUE TITLE
map downloader help page

### ISSUE THREAD

**Issue by gubuntu** [GordonFleming/SAGTAwebsite#4]
Set up a page where Mom, Brandon etc can write help documentation for the map downloader, as well as a link to Brandon's video. 

Then send me the url so I can put it in the help link in the downloader site.

**Comment by GordonFleming** [comment]
Help is now setup, just requires an editor or moderator to create a sub-page under the main help page. Whatever page is then made for the map downloader can then be used for the map downloader site.

Link should look something like: sagta.org.za/help/<map-downloader>

**Comment by gubuntu** [comment]
how do you mean help is now set up? where? (here? https://sagta.org.za/admin/pages/31)

I created this a year or two ago https://sagta.org.za/admin/pages/22/ for @bflouw to populate. See https://github.com/kartoza/SAGTA/issues/44.

Please delete the one you don't want and let us know which page to populate and link to

**Comment by GordonFleming** [comment]
Here is the help: https://sagta.org.za/admin/pages/30/
